version: "3.6"

services:
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
  tasks-service:
    build: "."
    depends_on:
    - "postgres"
    - "nats"
    ports:
    - "8080"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
  query-service:
    build: "."
    depends_on:
    - "postgres"
    - "nats"
    - "elasticsearch"
    ports:
    - "8080"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
