version: "3.6"

volumes:
  dataelasticsearch: {}
  datapostgres: {}
services:
  ui-service:
    build: "./ui-service"
    ports:
      - "80:80"
  postgres:
    build: "./devops/postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
    - "5432:5432"
    volumes:
      - datapostgres:/var/lib/postgresql/data
  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
    ports: 
    - "4222:4222"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    ports: 
    - "9200:9200"
    volumes:
      - dataelasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
  pusher-service:
    build: "."
    command: "pusher-service"
    depends_on:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
      LOG_LEVEL: "DEBUG"
      SERVICE_PORT: "8080"
  repository-service:
    build: "."
    command: "repository-service"
    depends_on:
    - "postgres"
    - "nats"
    ports:
    - "8080"
    environment:
      POSTGRES_ADDR: "postgres"
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
      LOG_LEVEL: "DEBUG"
      SERVICE_PORT: "8080"
  query-service:
    build: "."
    command: "query-service"
    depends_on:
    - "postgres"
    - "elasticsearch"
    ports:
    - "8080"
    environment:
      POSTGRES_ADDR: "postgres"
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
      LOG_LEVEL: "DEBUG"
      SERVICE_PORT: "8080"
  kaiser-service:
    build: "."
    command: "kaiser-service"
    depends_on:
      - "postgres"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_ADDR: "postgres"
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
      LOG_LEVEL: "DEBUG"
      SERVICE_PORT: "8080"
  load-balancer:
    build: "./devops/nginx"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - "8000:80"
    depends_on:
    - "repository-service"
    - "query-service"
    - "kaiser-service"