version: "3.6"

volumes:
  dataelasticsearch: {}
  datapostgres: {}
services:
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - datapostgres:/var/lib/postgresql/data
  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    volumes:
      - dataelasticsearch:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
  repository-service:
    build: "."
    command: "repository-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
  query-service:
    build: "."
    command: "query-service"
    depends_on:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    environment:
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
      ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  kaiser-service:
    build:
      context: "."
      dockerfile: "Dockerfile-Debug"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    command: "dlv --listen=:40000 --headless=true --api-version=2 exec kaiser-service"
    depends_on:
      - "postgres"
    ports:
      - "8080"
      - "40000:40000"
    environment:
      POSTGRES_ADDR: "postgres"
      POSTGRES_DB: "kaiserdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      NATS_ADDRESS: "nats:4222"
      LOG_LEVEL: "DEBUG"
      SERVICE_PORT: "8080"
  kong:
    image: kong:0.14.1-centos
    command: sh -c "kong migrations up && kong start --vv"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    depends_on:
      - "postgres"
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_DATABASE: "kongdb"
      KONG_PG_HOST: "postgres"
      KONG_PG_USER: "postgres"
      KONG_PG_PASSWORD: "postgres"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_LISTEN_SSL: "0.0.0.0:8444"
  kong-dashboard:
    image: pgbi/kong-dashboard:v3
    command: start --kong-url http://kong:8001
    depends_on:
      - "postgres"
      - "kong"
    ports:
      - "9000:8080"
  # nginx:
  #   build: "./nginx"
  #   ports:
  #   - "8080:80"
  #   depends_on:
  #   - "repository-service"
  #   - "query-service"