kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud-kaiser_kaiser-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-kaiser
      service: kaiser-service
  template:
    metadata:
      labels:
        app: cloud-kaiser
        service: kaiser-service
    spec:
      containers:
        - name: cloud-kaiser_kaiser-service
          image: cloud-kaiser_kaiser-service
          ports:
            - containerPort: 8085
          env:
            - name: POSTGRES_ADDR
              value: cloud-kaiser_postgres
            - name: POSTGRES_DB
              value: kaiserdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: NATS_ADDRESS
              value: nats-server:4222
            - name: LOG_LEVEL
              value: DEBUG
            - name: SERVICE_PORT
              value: 8085
---
kind: Service
apiVersion: v1
metadata:
  name: cloud-kaiser_kaiser-service
  labels:
    app: cloud-kaiser_kaiser-service
spec:
  selector:
    app: cloud-kaiser_kaiser-service
  type: LoadBalancer
  ports:
    - name: cloud-kaiser_kaiser-service
      port: 8085
      targetPort: 8085

